### ISSUE TITLE
size is not defined

### ISSUE THREAD

**Issue by eyadsibai** [bsvineethiitg/XTune-MLUtils#1]
https://github.com/bsvineethiitg/XTune-MLUtils/blob/b0d5ae5f617d8bf57038f11a238de704d38c4326/mltools.py#L425

**Comment by vinbhaskara** [comment]
Thank you for pointing out! size x size should have been len(data_array). I had implemented this in the context of images originally where len(data_array) = size x size for images of dimensions size x size. This has been now fixed in the latest commit. Thank you again!
